---

- name: Export Linuxmuster.net package lists
  hosts: localhost
  gather_facts: False
  vars:
    ansible_pkg_mgr: 'apt'
    ansible_virtualization_role: 'host'
    ansible_form_factor: 'Notebook'
    ansible_devices:
      'sda':
        rotational: '1'
    packages__localizations:
      - code: 'de'
        culture: 'de-de'
        name: 'german'
    packages__mode: 'export'
    packages__export_format: 'yaml'
    packages__export_key_name: 'linuxmuster_net_client__packages_preset_ypid'
    packages__export_key_absent_name: 'linuxmuster_net_client__packages_preset_ypid_absent'
    packages__export_directory: '{{ inventory_dir | realpath }}/../../apt_package_lists'
    packages__contrib_enabled: True
    packages__nonfree_enabled: True
    packages__export_classes:
      - 'client_school_linuxmuster'
    packages__reject_for_gymnasium: []
    packages__reject_for_class:

      client_school: '{{ packages__reject_for_school }}'
      client_school_linuxmuster: |
        {{
          packages__reject_for_school +
          packages__reject_for_gymnasium +
          packages__group_education_junior +
          packages__group_education_games +
          []
        }}


    packages__load_distribution_additional:
      - 'Linuxmint_qiana'
    packages__export_distributions:

      - ansible_distribution: 'Ubuntu'
        ansible_distribution_release: 'trusty'

  roles:
    - role: ypid.packages
